# Generated by Django 5.2.9 on 2025-12-10 19:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Market",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[("kalshi", "Kalshi"), ("polymarket", "Polymarket")],
                        max_length=20,
                    ),
                ),
                ("external_id", models.CharField(max_length=255)),
                ("event_external_id", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField(blank=True)),
                ("outcomes", models.JSONField(default=list)),
                ("url", models.URLField(blank=True, max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("close_time", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {("exchange", "external_id")},
            },
        ),
        migrations.CreateModel(
            name="MarketMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField(default=0.0)),
                (
                    "match_reason",
                    models.TextField(
                        blank=True, help_text="Why these markets were matched"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Manually verified as same event"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kalshi_market",
                    models.ForeignKey(
                        limit_choices_to={"exchange": "kalshi"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kalshi_matches",
                        to="markets.market",
                    ),
                ),
                (
                    "polymarket_market",
                    models.ForeignKey(
                        limit_choices_to={"exchange": "polymarket"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymarket_matches",
                        to="markets.market",
                    ),
                ),
            ],
            options={
                "unique_together": {("kalshi_market", "polymarket_market")},
            },
        ),
        migrations.CreateModel(
            name="ArbitrageOpportunity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arb_type",
                    models.CharField(
                        choices=[
                            ("kalshi_only", "Kalshi Only"),
                            ("polymarket_only", "Polymarket Only"),
                            ("cross_exchange", "Cross Exchange"),
                        ],
                        max_length=20,
                    ),
                ),
                ("positions", models.JSONField(default=dict)),
                ("profit_percent", models.FloatField()),
                ("expected_value", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "markets",
                    models.ManyToManyField(
                        related_name="arbitrage_opportunities", to="markets.market"
                    ),
                ),
                (
                    "market_match",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="arbitrage_opportunities",
                        to="markets.marketmatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-profit_percent", "-updated_at"],
            },
        ),
    ]
