# Generated by Django 5.2.9 on 2025-12-11 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange",
                    models.CharField(
                        choices=[("kalshi", "Kalshi"), ("polymarket", "Polymarket")],
                        max_length=20,
                    ),
                ),
                (
                    "external_id",
                    models.CharField(
                        blank=True, help_text="API's internal ID", max_length=255
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("slug", models.CharField(blank=True, max_length=255)),
                ("category", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["exchange", "category", "label"],
                "unique_together": {("exchange", "label", "category")},
            },
        ),
        migrations.AddField(
            model_name="market",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="markets", to="markets.tag"
            ),
        ),
        migrations.CreateModel(
            name="TagMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("similarity_score", models.FloatField(default=0.0)),
                (
                    "match_reason",
                    models.TextField(
                        blank=True, help_text="Why these tags were matched"
                    ),
                ),
                (
                    "is_manual",
                    models.BooleanField(
                        default=False, help_text="True if manually created by user"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kalshi_tag",
                    models.ForeignKey(
                        limit_choices_to={"exchange": "kalshi"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kalshi_tag_matches",
                        to="markets.tag",
                    ),
                ),
                (
                    "polymarket_tag",
                    models.ForeignKey(
                        limit_choices_to={"exchange": "polymarket"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="polymarket_tag_matches",
                        to="markets.tag",
                    ),
                ),
            ],
            options={
                "ordering": ["-similarity_score", "-updated_at"],
                "unique_together": {("kalshi_tag", "polymarket_tag")},
            },
        ),
    ]
