# Generated by Django 5.2.9 on 2025-12-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0006_remove_arbitrageopportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="resolution_source",
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="event",
            name="rules_primary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="rules_secondary",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="event",
            name="series_ticker",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="event",
            name="sub_title",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
