# Generated by Django 5.2.9 on 2025-12-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("markets", "0007_event_resolution_source_event_rules_primary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Lowercase normalized tag name",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text="Original display name", max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "events",
                    models.ManyToManyField(
                        blank=True, related_name="tags", to="markets.event"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
